# Generated by Django 4.2.3 on 2023-08-20 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="member",
            name="modified_by",
        ),
    ]
