# Generated by Django 4.2.3 on 2023-08-19 02:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("role", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="role",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="role",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="role",
            name="modified_date",
        ),
    ]
