# Generated by Django 4.2.3 on 2023-10-01 06:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Penalty",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "modified_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.BooleanField()),
                ("reason", models.CharField(max_length=255)),
                (
                    "target_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalty",
                        to="common.member",
                    ),
                ),
            ],
            options={
                "db_table": "penalty",
                "ordering": ["-created_date"],
            },
        ),
    ]
