# Generated by Django 4.2.3 on 2023-11-29 06:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_member_options_alter_role_options_and_more"),
        ("penalty", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="penalty",
            options={"verbose_name": "Penalty", "verbose_name_plural": "Penalties"},
        ),
        migrations.RemoveField(
            model_name="penalty",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="penalty",
            name="modified_date",
        ),
        migrations.AddField(
            model_name="penalty",
            name="created_by",
            field=models.CharField(
                db_column="PENALTY_CREATED_BY",
                default="system",
                max_length=30,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="penalty",
            name="created_datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="PENALTY_CREATED_DTTM",
                default=django.utils.timezone.now,
                verbose_name="Created Date Time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="penalty",
            name="modified_by",
            field=models.CharField(
                db_column="PENALTY_MODIFIED_BY",
                default="system",
                max_length=30,
                verbose_name="Modified By",
            ),
        ),
        migrations.AddField(
            model_name="penalty",
            name="modified_datetime",
            field=models.DateTimeField(
                auto_now=True,
                db_column="PENALTY_MODIFIED_DTTM",
                verbose_name="Modified Date Time",
            ),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="id",
            field=models.AutoField(
                db_column="PENALTY_PK", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="reason",
            field=models.CharField(db_column="PENALTY_REASON", max_length=255),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="target_member",
            field=models.ForeignKey(
                db_column="MEMBER_MEMBER_PK",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="penalty",
                to="common.member",
            ),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="type",
            field=models.BooleanField(db_column="PENALTY_TYPE"),
        ),
        migrations.AlterModelTable(
            name="penalty",
            table="PENALTY",
        ),
    ]
