# Generated by Django 4.2.3 on 2023-11-29 06:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("penalty", "0002_alter_penalty_options_remove_penalty_created_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="penalty",
            old_name="created_datetime",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="penalty",
            old_name="modified_datetime",
            new_name="modified_date",
        ),
    ]
