# Generated by Django 4.2.3 on 2023-08-20 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("penalty", "0002_alter_penalty_created_by_alter_penalty_modified_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="penalty",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="penalty",
            name="modified_by",
        ),
    ]
