# Generated by Django 4.2.3 on 2023-11-29 06:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"verbose_name": "Member", "verbose_name_plural": "Members"},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Role", "verbose_name_plural": "Roles"},
        ),
        migrations.RemoveField(
            model_name="member",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="member",
            name="modified_date",
        ),
        migrations.AlterModelTable(
            name="member",
            table="MEMBER",
        ),
        migrations.AlterModelTable(
            name="role",
            table="ROLE",
        ),
    ]
